params:
  test: testKeyword
  epochs: 30
  batch_size: 32
  n_classes: 10
  metric: accuracy
  optimizer: SGD
  validation_size: 5000 

artifacts:
  artifacts_dir: artifacts
  model_dr: model
  plots_dir: plots
  checkpoint_dir: checkpoints

logs:
  logs_dir: logs_dir
  general_logs: general_logs
